### ISSUE TITLE
Readmanga not working 

### ISSUE THREAD

**Issue by Simmkai** [Skittyblock/aidoku-community-sources#560]
While trying to open a chapter from any manga from the Readmanga it says "Failed to Load Chapter". I checked the web view, and it seems to work, puls the chapters open as usual.

Thank you for your time.

**Comment by Skittyblock** [comment]
the site gives me a 404, which I'm not sure if it's because I'm not in Russia or not, so I can't check. the source probably needs updating though

**Comment by SergeyMursatov** [comment]
I looked at the config file. You need to change the address to https://readmanga.live/. Can you do it, please?

**Comment by Skittyblock** [comment]
Yeah as I said, the site gives me a 404. I can't test.

**Comment by SergeyMursatov** [comment]
Maybe u can add new source with  https://readmanga.live/. And we will test it from Russia.

**Comment by Serrkkaa** [comment]
Please fix it

**Comment by rodion2** [comment]
@Skittyblock @SergeyMursatov ReadManga doesn't working because of incorrect way of scrapping page. Html with manga images will not have image links untill initial js script on page updates it. Hta means that request to readmanga page should be implemented via the webDriver to run js scripts to initiate src values for <img> tags.
